#! /bin/bash

echo_and_run() {
    echo "$@"
    $@
}

echo "*** Insert packet ***"
echo_and_run python3 send_packet.py 123

echo "*** Retrieving the aggregate value works from the processor API ***"
echo_and_run curl 'http://localhost:8090/api/processors/myproject/realtime/parameters/myproject/structure'

echo "*** Waiting for the parameter to be archived ***"
echo_and_run sleep 5

echo "*** Retrieving the aggregate from the archive API fails ***"
echo_and_run curl 'http://localhost:8090/api/archive/myproject/parameters/myproject/structure'

echo "*** But retrieving the aggregate member works ***"
curl 'http://localhost:8090/api/archive/myproject/parameters/myproject/structure.value'
